### ISSUE TITLE
Error generating standalone certificates of different nodes with same name

### ISSUE THREAD

**Issue by micafer** [indigo-dc/ansible-role-indigovr#15]
There is a problem in case of elastic clusters using this role. 
In these kind of clusters the same hostname (e.g. "vnode-1") is used for different VMs in different moments.
In a first step the role works. But when this node is deleted (the node is idle) and new jobs arrives to the cluster and a new VM is launched usign the same hostname the role fails.

This error appears when starting the openvpn service in the standalone client:

```
Oct 03 13:14:52 vnode-1.localdomain ovpn-standalone[5659]: WARNING: No server certificate verification method has been enabled. See http://openvpn.net/howto.html#mitm
Oct 03 13:14:52 vnode-1.localdomain ovpn-standalone[5659]: Cannot load private key file /etc/openvpn/certs/INDIGOVR-standalone-vnode-1.localdomain.key: error:0B080074:
Oct 03 13:14:52 vnode-1.localdomain ovpn-standalone[5659]: Error: private key password verification failed
```
The problem is here:
https://github.com/indigo-dc/ansible-role-indigovr/blob/master/tasks/standalone.yml#L20

As the certificate is not signed again and it is used the previous existing one.

But if you remove the "creates" argument in this task there is another error when signing the certificate:

```
Using configuration from /root/CA/openssl.cnf
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
name                  :PRINTABLE:'standalone'
commonName            :PRINTABLE:'vnode-1.localdomain'
Certificate is to be certified until Oct  2 14:02:07 2020 GMT (365 days)
failed to update database
TXT_DB error number 2
```

Could you help us to solve it?

/cc @maricaantonacci

**Comment by Majlen** [comment]
Hi Miguel,

The issue seems to come from the certificate having the same Common Name. Having the cluster dynamically resized during its lifetime was not accounted for as we thought that the cluster would be reasonably stable. The current design supports only extending.

To resolve this issue, you would need to revoke the old certificate (`openssl ca -revoke cert.pem ...`), which is possible, because the CA should have all the client certificates stored in `/root/CA/certs/`. Basically you would need to check, whether the certificate file already exists, and revoke it in that case.

Other possibility is to turn off the check for unique Common Names by setting `unique_subject = no` [here](https://github.com/indigo-dc/ansible-role-indigovr/blob/master/files/openssl-ca.cnf#L48).

@valtri or @sustr4 should help you with that further...

**Comment by valtri** [comment]
Thanks for the tips! I'll try implement and test the revoking.

**Comment by valtri** [comment]
I've created a branch `revoke` with the proposed changes. The certificate is revoked only, when the .csr file is newer then the .crt file (the newer version of .csr uploaded). 

It is probably a hack - the test is called inside a shell and ansible will consider the task as "changed" on each run.

**Comment by micafer** [comment]
Hi @valtri 

Using your solution I have proposed another change setting the test as an ansible task.
I will test it and let you know.

**Comment by valtri** [comment]
If I understand your change correctly - new certificates will be issued with each ansible run. I think we would need additional condition yet, like:

`test "{{ INDIGOVR_CA_DIR }}/certs/{{ INDIGOVR_CERT_NAME }}.csr" -nt "{{ INDIGOVR_CA_DIR }}/certs/{{ INDIGOVR_CERT_NAME }}.crt"`

But using `stat.mtime` it could be done quite nicely in ansible. :-)

**Comment by micafer** [comment]
Yes you are rigth. Let me fix it.

**Comment by micafer** [comment]
I think this solution is correct. I'm testing it.

**Comment by valtri** [comment]
Already merged, closing the issue. Thanks!
